#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawLimit,      sensorPotentiometer)
#pragma config(Sensor, in2,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in3,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in4,    leftLight,      sensorLineFollower)
#pragma config(Sensor, dgtl5,  outputSound,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393HighSpeed_HBridge, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393HighSpeed_HBridge, PIDControl, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Wait for Dark -                                          *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to wait until the lights around it go down to move forward for   *|
|*  1.5 seconds.  There is a two second pause at the beginning of the program.                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Lighting conditions change from place to place, so the value '200' may need to be changed   *|
|*        to better suit your environment.                                                            *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 8     lightSensor         VEX Light Sensor      Mounted facing up                 *|
\*-----------------------------------------------------------------------------------------------4246-*/

void turnLeft(){

	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
	wait1Msec(1000);
	moveMotorTarget(rightMotor, 525, 20, true);
	moveMotorTarget(leftMotor, -525, -20, true);

	while(getMotorTargetCompleted(rightMotor) == false && getMotorTargetCompleted(leftMotor) == false){
	}
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

void turnRight(){
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
	wait1Msec(1000);
	moveMotorTarget(rightMotor, -525, -20, true);
	moveMotorTarget(leftMotor, 525, 20, true);

	while(getMotorTargetCompleted(rightMotor) == false && getMotorTargetCompleted(leftMotor) == false){
	}
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

void GoForward(int target){
	if (target == NULL){
		target = 550;
	}
	nMotorEncoder[rightMotor] = 0;
	nMotorEncoder[leftMotor] = 0;
	setMotorTarget(rightMotor, target, 55, true);
	setMotorTarget(leftMotor, target, 55, true);
	while(getMotorTargetCompleted(rightMotor) == false && getMotorTargetCompleted(leftMotor) == false){
	}
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main(){
	nMotorEncoder[rightMotor] = 0;
	nMotorEncoder[leftMotor] = 0;
	setMotorTarget(rightMotor, target, 55, true);
	setMotorTarget(leftMotor, target, 55, true
	while(1){}
}
